name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (optional but recommended)
        uses: docker/setup-buildx-action@v3

      - name: Build & bring up services
        run: |
          # note: no hyphen here
          docker compose up --build -d
          docker compose ps

      - name: Run tests
        run: |
          pytest -q

      - name: Tear down
        if: always()
        run: |
          docker compose down
